CONN pdbadmin/password@northwind;

CREATE
  TABLE "SUPPLIERS"
  (
    "SUPPLIERID"   NUMBER NOT NULL enable
  , "COMPANYNAME"  VARCHAR2(50) NOT NULL enable
  , "CONTACTNAME"  VARCHAR2(30)
  , "CONTACTTITLE" VARCHAR2(30)
  , "ADDRESS"      VARCHAR2(60)
  , "CITY"         VARCHAR2(15)
  , "REGION"       VARCHAR2(15)
  , "POSTALCODE"   VARCHAR2(10)
  , "COUNTRY"      VARCHAR2(15)
  , "PHONE"        VARCHAR2(24)
  , "FAX"          VARCHAR2(24)
  , "HOMEPAGE" CLOB
  , CONSTRAINT "PK_SUPPLIERS" PRIMARY KEY ("SUPPLIERID") USING INDEX enable
  )
/
CREATE
  TABLE "CATEGORIES"
  (
    "CATEGORYID"   NUMBER NOT NULL enable
  , "CATEGORYNAME" VARCHAR2(15)
  , "DESCRIPTION" CLOB
  , CONSTRAINT "CATEGORIES_ID_PK" PRIMARY KEY ("CATEGORYID") USING INDEX enable
  )
/
CREATE
  TABLE "PRODUCTS"
  (
    "PRODUCTID"       NUMBER NOT NULL enable
  , "PRODUCTNAME"     VARCHAR2(50) NOT NULL enable
  , "SUPPLIERID"      NUMBER
  , "CATEGORYID"      NUMBER
  , "QUANTITYPERUNIT" VARCHAR2(20)
  , "UNITPRICE"       NUMBER DEFAULT 0
  , "UNITSINSTOCK"    NUMBER DEFAULT 0
  , "UNITSONORDER"    NUMBER DEFAULT 0
  , "REORDERLEVEL"    NUMBER DEFAULT 0
  , "DISCONTINUED"    NUMBER(1,0) DEFAULT 0
  , CONSTRAINT "PK_PRODUCTS" PRIMARY KEY ("PRODUCTID") USING INDEX enable
  , CONSTRAINT "CK_PRODUCTS_UNITPRICE" CHECK (unitprice >= 0) enable
  , CONSTRAINT "CK_REORDERLEVEL" CHECK (reorderlevel    >= 0) enable
  , CONSTRAINT "CK_UNITSINSTOCK" CHECK (unitsinstock    >= 0) enable
  , CONSTRAINT "CK_UNITSONORDER" CHECK (unitsonorder    >= 0) enable
  )
/
CREATE
  TABLE "EMPLOYEES"
  (
    "EMPLOYEEID"      NUMBER NOT NULL enable
  , "LASTNAME"        VARCHAR2(20) NOT NULL enable
  , "FIRSTNAME"       VARCHAR2(10) NOT NULL enable
  , "TITLE"           VARCHAR2(30)
  , "TITLEOFCOURTESY" VARCHAR2(25)
  , "BIRTHDATE"       DATE
  , "HIREDATE"        DATE
  , "ADDRESS"         VARCHAR2(60)
  , "CITY"            VARCHAR2(15)
  , "REGION"          VARCHAR2(15)
  , "POSTALCODE"      VARCHAR2(10)
  , "COUNTRY"         VARCHAR2(15)
  , "HOMEPHONE"       VARCHAR2(24)
  , "EXTENSION"       VARCHAR2(4)
  , "NOTES" CLOB
  , "REPORTSTO" NUMBER
  , "PHOTOPATH" VARCHAR2(255)
  , CONSTRAINT "PK_EMPLOYEES" PRIMARY KEY ("EMPLOYEEID") USING INDEX enable
  )
/
CREATE
  TABLE "SHIPPERS"
  (
    "SHIPPERID"   NUMBER NOT NULL enable
  , "COMPANYNAME" VARCHAR2(40) NOT NULL enable
  , "PHONE"       VARCHAR2(24)
  , CONSTRAINT "PK_SHIPPERS" PRIMARY KEY ("SHIPPERID") USING INDEX enable
  )
/
CREATE
  TABLE "CUSTOMERS"
  (
    "CUSTOMERID"   VARCHAR2(5) NOT NULL enable
  , "COMPANYNAME"  VARCHAR2(40) NOT NULL enable
  , "CONTACTNAME"  VARCHAR2(30)
  , "CONTACTTITLE" VARCHAR2(30)
  , "ADDRESS"      VARCHAR2(60)
  , "CITY"         VARCHAR2(20)
  , "REGION"       VARCHAR2(15)
  , "POSTALCODE"   VARCHAR2(10)
  , "COUNTRY"      VARCHAR2(15)
  , "PHONE"        VARCHAR2(24)
  , "FAX"          VARCHAR2(24)
  , CONSTRAINT "PK_CUSTOMERS" PRIMARY KEY ("CUSTOMERID") USING INDEX enable
  )
/
CREATE
  TABLE "ORDERS"
  (
    "ORDERID"        NUMBER NOT NULL enable
  , "CUSTOMERID"     VARCHAR2(5) NOT NULL enable
  , "EMPLOYEEID"     NUMBER
  , "ORDERDATE"      DATE
  , "REQUIREDDATE"   DATE
  , "SHIPPEDDATE"    DATE
  , "SHIPVIA"        NUMBER
  , "FREIGHT"        NUMBER DEFAULT 0
  , "SHIPNAME"       VARCHAR2(40)
  , "SHIPADDRESS"    VARCHAR2(60)
  , "SHIPCITY"       VARCHAR2(20)
  , "SHIPREGION"     VARCHAR2(15)
  , "SHIPPOSTALCODE" VARCHAR2(10)
  , "SHIPCOUNTRY"    VARCHAR2(15)
  , CONSTRAINT "PK_ORDERS" PRIMARY KEY ("ORDERID") USING INDEX enable
  )
/
CREATE
  TABLE "ORDERDETAILS"
  (
    "ORDERID"   NUMBER NOT NULL enable
  , "PRODUCTID" NUMBER NOT NULL enable
  , "UNITPRICE" NUMBER DEFAULT 0 NOT NULL enable
  , "QUANTITY"  NUMBER DEFAULT 1 NOT NULL enable
  , "DISCOUNT"  NUMBER DEFAULT 0 NOT NULL enable
  , CONSTRAINT "PK_ORDER_DETAILS" PRIMARY KEY ("ORDERID", "PRODUCTID") USING INDEX enable
  , CONSTRAINT "CK_DISCOUNT" CHECK (discount   >= 0
    AND discount                               <= 1) enable
  , CONSTRAINT "CK_QUANTITY" CHECK (quantity    > 0) enable
  , CONSTRAINT "CK_UNITPRICE" CHECK (unitprice >= 0) enable
  )
/
CREATE
  TABLE "CUSTOMERGROUPTHRESHOLDS"
  (
    "CUSTOMERGROUPNAME" VARCHAR2(20)
  , "RANGEBOTTOM"       NUMBER
  , "RANGETOP"          NUMBER
  )
/

CREATE sequence "CATEGORIES_SEQ" minvalue 1 maxvalue 9999999999999999999999999999 increment BY 1
START WITH 9 cache 20 noorder nocycle nokeep noscale global
/
CREATE sequence "EMPLOYEES_SEQ" minvalue 1 maxvalue 9999999999999999999999999999 increment BY 1
START WITH 10 cache 20 noorder nocycle nokeep noscale global
/
CREATE sequence "ORDERS_SEQ" minvalue 1 maxvalue 9999999999999999999999999999 increment BY 1
START WITH 11078 cache 20 noorder nocycle nokeep noscale global
/
CREATE sequence "PRODUCTS_SEQ" minvalue 1 maxvalue 9999999999999999999999999999 increment BY 1
START WITH 78 cache 20 noorder nocycle nokeep noscale global
/
CREATE sequence "SHIPPERS_SEQ" minvalue 1 maxvalue 9999999999999999999999999999 increment BY 1
START WITH 4 cache 20 noorder nocycle nokeep noscale global
/
CREATE sequence "SUPPLIERS_SEQ" minvalue 1 maxvalue 9999999999999999999999999999 increment BY 1
START WITH 30 cache 20 noorder nocycle nokeep noscale global 
/
