CONN pdbadmin/password@northwind;

ALTER TABLE "EMPLOYEES" ADD CONSTRAINT "FK_EMPLOYEES_EMPLOYEES" FOREIGN KEY ("REPORTSTO") REFERENCES "EMPLOYEES" ("EMPLOYEEID") enable
/
ALTER TABLE "ORDERDETAILS" ADD CONSTRAINT "FK_ORDER_DETAILS_ORDERS" FOREIGN KEY ("ORDERID") REFERENCES "ORDERS" ("ORDERID") enable
/
ALTER TABLE "ORDERDETAILS" ADD CONSTRAINT "FK_ORDER_DETAILS_PRODUCTS" FOREIGN KEY ("PRODUCTID") REFERENCES "PRODUCTS" ("PRODUCTID") enable
/
ALTER TABLE "ORDERS" ADD CONSTRAINT "FK_ORDERS_CUSTOMERS" FOREIGN KEY ("CUSTOMERID") REFERENCES "CUSTOMERS" ("CUSTOMERID") enable
/
ALTER TABLE "ORDERS" ADD CONSTRAINT "FK_ORDERS_EMPLOYEES" FOREIGN KEY ("EMPLOYEEID") REFERENCES "EMPLOYEES" ("EMPLOYEEID") enable
/
ALTER TABLE "ORDERS" ADD CONSTRAINT "FK_ORDERS_SHIPPERS" FOREIGN KEY ("SHIPVIA") REFERENCES "SHIPPERS" ("SHIPPERID") enable
/
ALTER TABLE "PRODUCTS" ADD CONSTRAINT "FK_PRODUCTS_CATEGORIES" FOREIGN KEY ("CATEGORYID") REFERENCES "CATEGORIES" ("CATEGORYID") enable
/
ALTER TABLE "PRODUCTS" ADD CONSTRAINT "FK_PRODUCTS_SUPPLIERS" FOREIGN KEY ("SUPPLIERID") REFERENCES "SUPPLIERS" ("SUPPLIERID") enable
/
